#!/bin/bash
# Created: 2026-01-19
# DANGEROUS COMMAND BLOCKER - Prevents destructive operations
# BLOCKS: docker prune, rm without trash, system deletions

# SIGPIPE trap - prevents ERR_STREAM_DESTROYED
trap '' SIGPIPE
set +e

# Fast-path: skip all checks for safe commands (before expensive input parsing)
if [ -n "${CLAUDE_TOOL_INPUT:-}" ]; then
    _FAST_CMD=$(printf '%s\n' "$CLAUDE_TOOL_INPUT" | jq -r '.command // empty' 2>/dev/null)
    if [ -n "$_FAST_CMD" ]; then
        # Block chained commands from abusing fast-path (ls; rm -rf /)
        case "$_FAST_CMD" in *\;*|*\&\&*|*\|\|*|*\|*|*\`*|*\$\(*) ;; *)
        case "${_FAST_CMD%% *}" in
            ls|echo|cat|head|tail|wc|date|pwd|whoami|uname|jq|curl|grep|rg|awk|sed|sort|uniq|tr|cut|tee|touch|mkdir|stat|file|which|type|test|\[)
                exit 0 ;;
        esac ;; esac
    fi
fi

# Load shared initialization
HOOKSHIELD_HOME="${HOOKSHIELD_HOME:-$HOME/.hookshield}"
if [ -f "${HOOKSHIELD_HOME}/lib/input-parser.sh" ]; then
    source "${HOOKSHIELD_HOME}/lib/input-parser.sh"
    parse_tool_input
fi

# Get the command - try multiple sources
COMMAND=""

# Method 0: From input-parser.sh (CONTENT is populated for Bash tools)
if [ -n "$CONTENT" ]; then
    COMMAND="$CONTENT"
fi

# Method 1: From parsed TOOL_INPUT (JSON) - try .tool_input.command first
if [ -z "$COMMAND" ] && [ -n "$TOOL_INPUT" ]; then
    COMMAND=$(printf '%s\n' "$TOOL_INPUT" | jq -r '.tool_input.command // .command // empty' 2>/dev/null)
fi

# Method 2: From CLAUDE environment
if [ -z "$COMMAND" ] && [ -n "${CLAUDE_TOOL_INPUT:-}" ]; then
    COMMAND=$(printf '%s\n' "$CLAUDE_TOOL_INPUT" | jq -r '.command // empty' 2>/dev/null)
fi

# Method 3: Read from stdin if nothing else worked (stdin may be consumed)
if [ -z "$COMMAND" ]; then
    if [ ! -t 0 ]; then
        STDIN_INPUT=$(timeout 2s cat 2>/dev/null || echo "")
        if [ -n "$STDIN_INPUT" ]; then
            COMMAND=$(printf '%s\n' "$STDIN_INPUT" | jq -r '.tool_input.command // .command // empty' 2>/dev/null)
        fi
    fi
fi

# Exit if no command found (not a Bash call or parsing failed)
if [ -z "$COMMAND" ]; then
    exit 0
fi

# =============================================================================
# SYMLINK BLOCK (AP1: No symlinks)
# =============================================================================
if printf '%s\n' "$COMMAND" | grep -qE '\bln\s+(-s|--symbolic)\b'; then
    echo "BLOCKED: Symlinks are FORBIDDEN (AP1). Use cp instead." >&2
    exit 2
fi

# =============================================================================
# FIND -DELETE / -EXEC RM BLOCK (destructive recursive find)
# =============================================================================
if printf '%s\n' "$COMMAND" | grep -qiE '\bfind\b.*(-delete|-exec\s+rm)'; then
    # Allow safe targets: __pycache__, .pyc, .tmp, node_modules, build artifacts
    if ! printf '%s\n' "$COMMAND" | grep -qiE '(__pycache__|\.pyc|\.tmp|\.bak|\.swp|\.log|node_modules|\.next|dist|build|\.pytest_cache)'; then
        echo "BLOCKED: find with -delete/-exec rm on non-artifact paths is FORBIDDEN" >&2
        echo "Tip: Only use find -delete on build artifacts (__pycache__, .pyc, .tmp, node_modules)" >&2
        exit 2
    fi
fi

# =============================================================================
# BLOCKED COMMANDS - NEVER ALLOW (exit 2 = hard block)
# =============================================================================

# Block git add of sensitive files
if printf '%s\n' "$COMMAND" | grep -qE 'git\s+(add|stage)'; then
    if printf '%s\n' "$COMMAND" | grep -qiE '\.(kdbx|p12|pfx|jks|keystore|pem|key|db|sqlite|sqlite3)\b|passwords\.|\.paperclip|auth-profiles|\.env(\.[a-z]+)?(\s|$)'; then
        echo "BLOCKED: git add of sensitive file (secrets/db/keys/env)" >&2
        exit 2
    fi
fi

# AI commit signature block (merged from no-commit-signatures.sh)
if printf '%s\n' "$COMMAND" | grep -qE 'git\s+commit'; then
    if printf '%s\n' "$COMMAND" | grep -qiE '(Co-Authored-By|Generated by AI|AI-assisted|noreply@anthropic|claude-opus|claude-sonnet|claude-haiku|Generated with Claude|Generated with \[Claude)'; then
        echo "BLOCKED: AI signatures/attribution not allowed in commits" >&2
        exit 2
    fi
fi

# Git force push to main/master - ALWAYS BLOCK (both flag orderings)
if printf '%s\n' "$COMMAND" | grep -qiE 'git\s+push\s+.*(--force|--force-with-lease|-f)\s+.*\b(main|master)\b'; then
    echo "BLOCKED: git force push to main/master is FORBIDDEN" >&2
    exit 2
fi
if printf '%s\n' "$COMMAND" | grep -qiE 'git\s+push\s+.*\b(main|master)\b.*(--force|--force-with-lease|-f)'; then
    echo "BLOCKED: git force push to main/master is FORBIDDEN" >&2
    exit 2
fi

# Docker prune commands - ALWAYS BLOCK
if printf '%s\n' "$COMMAND" | grep -qiE 'docker\s+(system\s+)?prune'; then
    echo "BLOCKED: docker prune commands are FORBIDDEN" >&2
    echo "Reason: Previous incident deleted 15 Docker images" >&2
    echo "Action: Ask user for explicit permission first" >&2
    exit 2
fi

# Docker volume prune - ALWAYS BLOCK
if printf '%s\n' "$COMMAND" | grep -qiE 'docker\s+volume\s+prune'; then
    echo "BLOCKED: docker volume prune is FORBIDDEN" >&2
    echo "Reason: Could delete important persistent data" >&2
    exit 2
fi

# Docker image prune - ALWAYS BLOCK
if printf '%s\n' "$COMMAND" | grep -qiE 'docker\s+image\s+prune'; then
    echo "BLOCKED: docker image prune is FORBIDDEN" >&2
    echo "Reason: Could delete important images" >&2
    exit 2
fi

# Docker rmi -f with wildcards or variables
if printf '%s\n' "$COMMAND" | grep -qiE 'docker\s+rmi.*(\$|\*|xargs)'; then
    echo "BLOCKED: Bulk docker image removal is FORBIDDEN" >&2
    exit 2
fi

# P0 FIX 2026-01-27: Docker command substitution patterns
# Docker with command substitution $(...) - BLOCK
if printf '%s\n' "$COMMAND" | grep -qiE 'docker\s+\w+.*\$\('; then
    echo "BLOCKED: docker with command substitution is FORBIDDEN" >&2
    echo "Reason: Could execute bulk destructive operations" >&2
    exit 2
fi

# Docker with backticks `...` - BLOCK
if printf '%s\n' "$COMMAND" | grep -qE 'docker\s+\w+.*`'; then
    echo "BLOCKED: docker with backtick substitution is FORBIDDEN" >&2
    exit 2
fi

# Pipe to docker destructive commands - BLOCK
if printf '%s\n' "$COMMAND" | grep -qiE '\|\s*(xargs\s+)?docker\s+(rm|rmi|stop|kill|prune)'; then
    echo "BLOCKED: piping to docker destructive commands is FORBIDDEN" >&2
    exit 2
fi

# Eval/bash -c with docker - BLOCK
if printf '%s\n' "$COMMAND" | grep -qiE '(eval|bash\s+-c|sh\s+-c).*docker.*(prune|rm|rmi)'; then
    echo "BLOCKED: indirect docker execution is FORBIDDEN" >&2
    exit 2
fi

# Docker images -q piped - BLOCK (precursor to bulk delete)
if printf '%s\n' "$COMMAND" | grep -qiE 'docker\s+(images|ps)\s+(-a\s+)?-q.*\|'; then
    echo "BLOCKED: docker listing with -q piped is FORBIDDEN" >&2
    echo "Reason: Commonly used for bulk deletion" >&2
    exit 2
fi

# =============================================================================
# RM SAFETY: block truly destructive deletes, allow normal cleanup
# Philosophy: rm is essential. Block catastrophic (root, system dirs, home).
#             Allow project cleanup (__pycache__, .pyc, .tmp, build artifacts).
# =============================================================================

# SAFE PATTERNS - always allow (exit before any rm checks)
# Temp/build artifacts, caches, logs, test outputs
if printf '%s\n' "$COMMAND" | grep -qiE 'rm\s+.*(__pycache__|\.pyc|\.pyo|\.tmp|\.bak|\.swp|\.log|\.tsbuildinfo|node_modules|\.next|dist/|build/|\.pytest_cache|\.mypy_cache|\.coverage|htmlcov|\.eggs|\.egg-info)'; then
    # Safe cleanup targets - allow
    :
# rm -rf / or rm -rf /* (catastrophic root delete)
elif printf '%s\n' "$COMMAND" | grep -qiE 'rm\s+(-[rRf]+\s+)+/(\s|$|\*)'; then
    echo "BLOCKED: rm on filesystem root is FORBIDDEN" >&2
    echo "Reason: Would destroy the entire system" >&2
    exit 2
# rm on TOP-LEVEL system directories (only the dir itself, not deep paths)
# /var, /etc, /usr, /boot, /lib, /opt - these are OS dirs
# /home and /root - user home dirs
# NOTE: /data is NOT blocked because projects live there. Only /data itself is blocked.
elif printf '%s\n' "$COMMAND" | grep -qiE 'rm\s+(-[rRf]+\s+)+/(var|etc|usr|boot|lib|opt|home|root|data)/?(\s|$)'; then
    echo "BLOCKED: rm on top-level system directory is FORBIDDEN" >&2
    echo "Reason: Could destroy system or user data" >&2
    echo "Tip: Be more specific - delete the exact subdirectory/file instead" >&2
    exit 2
# rm -rf on docker paths (protect container data)
elif printf '%s\n' "$COMMAND" | grep -qiE 'rm\s+(-[rRf]+\s+)+.*/docker/?(\s|$)'; then
    echo "BLOCKED: rm on docker directory is FORBIDDEN" >&2
    exit 2
# rm -rf on top-level home dot-dirs (protect config, not subdirs)
elif printf '%s\n' "$COMMAND" | grep -qiE 'rm\s+(-[rRf]+\s+)+(~|/home/[^/]+)/\.(gradle|cache|local|config|ssh|gnupg|claude)/?(\s|$)'; then
    echo "BLOCKED: rm on important home directory is FORBIDDEN" >&2
    echo "Tip: Delete specific subdirectory instead (e.g. ~/.cache/pip/)" >&2
    exit 2
# rm with sudo on system paths (extra caution)
elif printf '%s\n' "$COMMAND" | grep -qiE 'sudo\s+rm\s+(-[rRf]+\s+)+/(var|etc|usr|boot|lib|opt|home|root)'; then
    echo "BLOCKED: sudo rm on system directory is FORBIDDEN" >&2
    exit 2
fi

# noDeletePaths: protect critical project files from deletion
if printf '%s\n' "$COMMAND" | grep -qiE '(rm|git\s+rm|unlink|find\s.*-delete)\s'; then
    if printf '%s\n' "$COMMAND" | grep -qiE '(CLAUDE\.md|BRAIN\.md|LICENSE|README\.md|Dockerfile|docker-compose\.yml|\.gitignore|\.github/)'; then
        echo "BLOCKED: Cannot delete protected project file (noDeletePaths)" >&2
        exit 2
    fi
fi

# =============================================================================
# All checks passed - allow command
# =============================================================================
exit 0
